---
- name: Configure OIDC
  ansible.builtin.include_tasks: infra/oidc.yml

- name: Configure Storage
  ansible.builtin.include_tasks: infra/storage.yml

- name: Configure Events
  ansible.builtin.include_tasks: infra/events.yml
